name: Artifacts Download and Upload Practice
on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Folder
        run: |
          mkdir build
          touch build/example-file

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact # name to reference the artifact
          path: build
        



  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          # path: build

      - name: Print Contents of Artifact
        run: |
          ls -R
        
  
